In [51]:
import numpy as np

In [55]:
arr_2d = np.array([[3,5,4], [1,6,2], [8,4,6]])

In [58]:
arr_2d

array([[3, 5, 4],
       [1, 6, 2],
       [8, 4, 6]])

In [59]:
arr_2d[1,1]

6

In [60]:
arr_2d[2][1]

4

In [61]:
arr_2d[:2, 1:]

array([[5, 4],
       [6, 2]])

In [62]:
arr_2d[1:,:2]

array([[1, 6],
       [8, 4]])

In [63]:
arr_2d[:2]

array([[3, 5, 4],
       [1, 6, 2]])

In [10]:
arr_2d[:,1:]

array([[5, 4],
       [6, 2],
       [4, 6]])

In [64]:
arr = np.array([list(np.random.randint(1,20,5)), list(np.random.randint(1,20,5)), list(np.random.randint(1,20,5)), list(np.random.randint(1,20,5))])

In [65]:
arr

array([[19, 16, 16, 16, 10],
       [ 7, 11, 17, 16, 15],
       [ 9,  4, 13, 12, 10],
       [ 4, 13, 17,  9, 13]])

In [66]:
arr[1:3,2:4]

array([[17, 16],
       [13, 12]])

In [67]:
arr[:2]

array([[19, 16, 16, 16, 10],
       [ 7, 11, 17, 16, 15]])

In [68]:
arr[:,:2]

array([[19, 16],
       [ 7, 11],
       [ 9,  4],
       [ 4, 13]])

In [69]:
arr = np.arange(10)

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
bool_arr = arr > 5

In [72]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [73]:
arr[bool_arr]

array([6, 7, 8, 9])

In [75]:
arr[arr>5]

array([6, 7, 8, 9])

In [76]:
arr_2d = np.arange(50).reshape(5,10)

In [77]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [78]:
arr_2d[2:, 5:8]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [79]:
arr = np.arange(0,11)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [86]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [87]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [88]:
arr/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
arr2 = np.arange(0,12)

In [46]:
arr+arr2

ValueError: operands could not be broadcast together with shapes (11,) (12,) 

In [47]:
1/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [48]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [49]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
np.average(arr)

5.0